accounts_income_schema = [
    {"name": "income_id", "type": "INTEGER", "pk": True},
    {"name": "transaction_type", "type": "TEXT"},
    {"name": "plant_id", "type": "INTEGER"},
    {"name": "transaction_mode", "type": "TEXT"},
    {"name": "consignor_id", "type": "INTEGER"},
    {"name": "account_id", "type": "INTEGER"},
    {"name": "date", "type": "DATE"},
    {"name": "time", "type": "TIME"},
    {"name": "itype", "type": "TEXT"},
    {"name": "icode", "type": "TEXT"},
    {"name": "consignee_id", "type": "INTEGER"},
    {"name": "employee_id", "type": "INTEGER"},
    {"name": "vendor_id", "type": "INTEGER"},
    {"name": "transporter_id", "type": "INTEGER"},
    {"name": "bill_id", "type": "INTEGER"},
    {"name": "bill_name", "type": "TEXT"},
    {"name": "particulars", "type": "TEXT"},
    {"name": "transaction_amount", "type": "NUMERIC"},
    {"name": "authorized_by", "type": "TEXT"},
    {"name": "authorized_by_name", "type": "TEXT"},
    {"name": "created_on", "type": "DATETIME"},
    {"name": "created_by", "type": "TEXT"},
    {"name": "status", "type": "TEXT"},
    {"name": "active_ind", "type": "TEXT"},
    {"name": "income_type", "type": "TEXT"},
    {"name": "advance_id", "type": "INTEGER"},
    {"name": "breakup_amount", "type": "NUMERIC"},
    {"name": "treasury_amount", "type": "NUMERIC"},
    {"name": "last_edited_by", "type": "TEXT"},
    {"name": "account_updated_on", "type": "DATETIME"},
]

accounts_expense_schema = [
    {"name": "expense_id", "type": "INTEGER", "pk": True},
    {"name": "transaction_type", "type": "TEXT"},
    {"name": "plant_id", "type": "INTEGER"},
    {"name": "transaction_mode", "type": "TEXT"},
    {"name": "consignor_id", "type": "INTEGER"},
    {"name": "account_id", "type": "INTEGER"},
    {"name": "date", "type": "DATE"},
    {"name": "time", "type": "TIME"},
    {"name": "itype", "type": "TEXT"},
    {"name": "icode", "type": "TEXT"},
    {"name": "consignee_id", "type": "INTEGER"},
    {"name": "employee_id", "type": "INTEGER"},
    {"name": "vendor_id", "type": "INTEGER"},
    {"name": "transporter_id", "type": "INTEGER"},
    {"name": "bill_id", "type": "INTEGER"},
    {"name": "bill_name", "type": "TEXT"},
    {"name": "particulars", "type": "TEXT"},
    {"name": "transaction_amount", "type": "NUMERIC"},
    {"name": "authorized_by", "type": "TEXT"},
    {"name": "authorized_by_name", "type": "TEXT"},
    {"name": "created_on", "type": "DATETIME"},
    {"name": "created_by", "type": "TEXT"},
    {"name": "status", "type": "TEXT"},
    {"name": "active_ind", "type": "TEXT"},
    {"name": "expense_type", "type": "TEXT"},
    {"name": "suspense_id", "type": "INTEGER"},
    {"name": "advance_id", "type": "INTEGER"},
    {"name": "breakup_amount", "type": "NUMERIC"},
    {"name": "treasury_amount", "type": "NUMERIC"},
    {"name": "bill_exist_status", "type": "TEXT"},
    {"name": "last_edited_by", "type": "TEXT"},
    {"name": "account_updated_on", "type": "DATETIME"},
]